### ISSUE TITLE
Link to TwiML app points to project that is not set up to generate the right token

### ISSUE THREAD

**Issue by devinrader** [TwilioDevEd/chat-quickstart-objc#3]
The README points to this repo: 

https://github.com/twilio/mobile-quickstart

As a solution for quickly standing up a server to generate a token.  The problem is that I don;t actually think this app generates the right kind of token.

Additionally, the repo contains a python app whereas the quickstart code points to a PHP file.

**Comment by kwhinnery** [comment]
new README fixes this
